dast:
  needs: deploy
  name: DAST Scan
  runs-on: ubuntu-latest
  steps:
    - name: Run ZAP OWASP full scan
      uses: zaproxy/action-full-scan@v0.9.0
      with:
        target: ${{ env.APP_URL }}
        token: ${{ secrets.GITHUB_TOKEN }}
        cmd_options: '-a -j -l WARN -r report_html.html'
        allow_issue_writing: true

    - name: Upload html report
      uses: actions/upload-artifact@v4
      with:
        name: DAST_Report
        path: report_html.html
