name: 40 SAST

on:
  workflow_dispatch:
  workflow_call:

jobs:
  SAST-CodeQL:
    name: Build and SAST CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download build artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: target
          path: ${{ github.workspace }}/target
        continue-on-error: true
      - name: Set up JDK 11
        if: steps.download-artifact.outcome != 'success'
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Ensure mvnw is executable
        if: steps.download-artifact.outcome != 'success'
        run: |
          if [ -f mvnw ]; then
            chmod +x mvnw
            ./mvnw --version
          else
            echo "mvnw not found. Generating Maven Wrapper..."
            mvn -N wrapper:wrapper
            chmod +x mvnw
          fi
      - name: Build with Maven
        if: steps.download-artifact.outcome != 'success'
        run: |
          ./mvnw clean package -B -Dmaven.test.skip || { echo "Maven build failed"; exit 1; }
          echo "Listing target directory:"
          ls -lR ${{ github.workspace }}/target
          echo "Listing src/main/java:"
          ls -lR src/main/java
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          debug: true
          source-root: src/main/java
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
          output: ${{ github.workspace }}/codeql-results
        continue-on-error: true
      - name: Upload CodeQL SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/codeql-results
        if: always()

  spotbugs:
    name: SAST SpotBugs
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download build artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: target
          path: ${{ github.workspace }}/target
        continue-on-error: true
     
