name: 20 SCA
on:
  workflow_dispatch:
  workflow_call:
jobs:
  sca:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        manifest_file: [ "pom.xml" ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    name: SCA Java project
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Ensure mvnw is executable
        run: |
          if [ -f mvnw ]; then
            chmod +x mvnw
            ./mvnw --version
          else
            echo "mvnw not found. Generating Maven Wrapper..."
            mvn -N wrapper:wrapper
            chmod +x mvnw
          fi
      - name: Install SCA tool (CRDA)
        id: install_crda
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: "0.2.5" # Latest available version
        continue-on-error: true
      - name: SCA (CRDA) Scan
        id: crda_scan
        uses: redhat-actions/crda@master
        with:
          manifest_file: ${{ matrix.manifest_file }}
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          fail_on: never
        continue-on-error: true
      - name: Fallback CRDA Scan (Manual)
        if: ${{ failure() }}
        run: |
          echo "Attempting manual CRDA scan with updated endpoint..."
          if [ -f /home/runner/work/_temp/openshift-bin/crda ]; then
            /home/runner/work/_temp/openshift-bin/crda config set api_url https://f8a-analytics.redhat.com
            /home/runner/work/_temp/openshift-bin/crda auth --snyk-token ${{ secrets.SNYK_TOKEN }}
            /home/runner/work/_temp/openshift-bin/crda analyze --file ${{ matrix.manifest_file }} --json-file-output crda-report.json --sarif-file-output crda-report.sarif
          else
            echo "CRDA binary not found. Skipping manual scan."
          fi
        continue-on-error: true
      - name: Install Snyk CLI (Fallback)
        if: ${{ failure() }}
        run: |
          echo "Installing Snyk CLI as fallback..."
          curl -sSL https://github.com/snyk/cli/releases/download/v1.1292.2/snyk-linux -o snyk
          chmod +x snyk
          mv snyk /usr/local/bin/
      - name: Snyk SCA Scan (Fallback)
        id: snyk_scan
        if: ${{ failure() }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          echo "Authenticating with Snyk..."
          snyk auth $SNYK_TOKEN || { echo "Snyk auth failed"; exit 1; }
          echo "Running Snyk test..."
          snyk test --file=${{ matrix.manifest_file }} --json-file-output=snyk-report.json --sarif-file-output=snyk-report.sarif -d
        continue-on-error: true
      - name: Print JSON analysis report
        if: ${{ always() }}
        run: |
          if [ -f crda-report.json ]; then
            echo "CRDA JSON report:"
            cat crda-report.json
          elif [ -f snyk-report.json ]; then
            echo "Snyk JSON report:"
            cat snyk-report.json
          else
            echo "No JSON report generated"
          fi
      - name: Print SARIF analysis report
        if: ${{ always() }}
        run: |
          if [ -f crda-report.sarif ]; then
            echo "CRDA SARIF report:"
            cat crda-report.sarif
          elif [ -f snyk-report.sarif ]; then
            echo "Snyk SARIF report:"
            cat snyk-report.sarif
          else
            echo "No SARIF report generated"
          fi
      - name: Upload SARIF report
        if: ${{ always() && (steps.crda_scan.outcome == 'success' || steps.snyk_scan.outcome == 'success') }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.crda_scan.outcome == 'success' && 'crda-report.sarif' || 'snyk-report.sarif' }}
      - name: Print Report Link
        if: ${{ always() && steps.crda_scan.outcome == 'success' }}
        run: echo ${{ steps.crda_scan.outputs.report_link }}
      - name: Print Artifact Name
        if: ${{ always() && steps.crda_scan.outcome == 'success' }}
        run: echo ${{ steps.crda_scan.outputs.artifact_name }}
      - name: Print Snyk Monitor Link
        if: ${{ always() && steps.snyk_scan.outcome == 'success' }}
        run: snyk monitor --file=${{ matrix.manifest_file }}
