name: 20 SCA
on:
  workflow_dispatch:
  workflow_call:
jobs:
  sca:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        manifest_file: [ "pom.xml" ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    name: SCA Java project
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Install Snyk CLI
        run: |
          curl -sSL https://github.com/snyk/cli/releases/download/v1.1292.2/snyk-linux -o snyk
          chmod +x snyk
          mv snyk /usr/local/bin/
      - name: Snyk SCA Scan
        id: snyk_scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN
          snyk test --file=${{ matrix.manifest_file }} --json-file-output=snyk-report.json --sarif-file-output=snyk-report.sarif
      - name: Print JSON analysis report
        if: ${{ always() }}
        run: cat snyk-report.json
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-report.sarif
      - name: Print Snyk Monitor Link
        run: snyk monitor --file=${{ matrix.manifest_file }}
